name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner
        run: |
          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=my_project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://YOUR_SONARQUBE_SERVER:9000

        
 
