name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        PORT: 8000
      run: |         
        echo $USER
        echo $PASS
        docker build . --file Dockerfile --tag arunvel1988/duasp-ci-demo-2025:latest
        docker login -u $USER -p $PASS
        
        docker push arunvel1988/duasp-ci-demo-2025:latest
        cat /etc/os-release
        sudo snap install ngrok
        docker run -d --name duasp -p "$PORT:$PORT" arunvel1988/duasp-ci-demo-2025:latest
        sudo ngrok config add-authtoken 1Sq8nUiBW6PmjrJLTF1RWJbzHkY_LndRpPp2iTA1sjQNbNhG
        ngrok http 8000
        
 
